/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irrgarten.UI;
import irrgarten.Directions;
import irrgarten.GameState;

/**
 *
 * @author Sergio Salvador Gil
 */
public class GraphicUI extends javax.swing.JFrame implements UI {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GraphicUI.class.getName());
    
    Cursors cursors = new Cursors(this,true);
    
    /**
     * Creates new form GraphicUI
     */
    public GraphicUI() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPlayers = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMonsters = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaLabyrinth = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jLabelCurrent = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setLabelFor(jTextAreaMonsters);
        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaPlayers.setColumns(20);
        jTextAreaPlayers.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jTextAreaPlayers.setRows(5);
        jTextAreaPlayers.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextAreaPlayersInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaPlayers);

        jTextAreaMonsters.setColumns(20);
        jTextAreaMonsters.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jTextAreaMonsters.setRows(5);
        jTextAreaMonsters.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextAreaMonstersInputMethodTextChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaMonsters);

        jTextAreaLabyrinth.setColumns(20);
        jTextAreaLabyrinth.setFont(new java.awt.Font("TlwgMono", 0, 16)); // NOI18N
        jTextAreaLabyrinth.setRows(5);
        jTextAreaLabyrinth.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 160, 10, 30));
        jScrollPane3.setViewportView(jTextAreaLabyrinth);

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jTextAreaLog.setRows(5);
        jTextAreaLog.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jScrollPane4.setViewportView(jTextAreaLog);

        jLabelCurrent.setFont(new java.awt.Font("Ubuntu Mono", 0, 15)); // NOI18N
        jLabelCurrent.setText("------------------");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAreaPlayersInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextAreaPlayersInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaPlayersInputMethodTextChanged

    private void jTextAreaMonstersInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextAreaMonstersInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAreaMonstersInputMethodTextChanged

    public void showGame(GameState gameState){
        jTextAreaLabyrinth.setText(gameState.getLabyrinth());
        jTextAreaLog.setText(gameState.getLog());
        jTextAreaMonsters.setText(gameState.getMonsters());
        jTextAreaPlayers.setText(gameState.getPlayers());
        
        jLabelCurrent.setText("Current Player:"+gameState.getCurrentPlayer());
        if (gameState.isWinner()){
            jLabelCurrent.setText("Game has finished");
        }
        this.repaint();
    }
    
    @Override
    public Directions nextMove(){
        return cursors.getDirection();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCurrent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaLabyrinth;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextArea jTextAreaMonsters;
    private javax.swing.JTextArea jTextAreaPlayers;
    // End of variables declaration//GEN-END:variables
}
